language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t ajpj40/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ajpj40/docker-react npm run test

